### ISSUE TITLE
Add styleClass attribute to more generically define L&F

### ISSUE THREAD

**Issue by kukel** [sknitelius/jsfwarn#1]
So you can more generically defile look and feel in a css file. So for jquery-ui based compponents you can add the `ui-state-error` or `ui-state-highlight` class to inputs

**Comment by sknitelius** [comment]
Optional styleClass attribute will be added.

For more flexibility infoClass, warningClass, errorClass and fatalClass will also be added. These will be set according to the FacesMessage severity level.

**Comment by sknitelius** [comment]
I have released a first implementation with jsfwarn-0.1.0-alpha1. 
At the moment only a subset of UIInput components is supported.

Default style application has been removed.

**Comment by sknitelius** [comment]
jsf-warn-0.1.0-alpha2 provides generic UIComponent styleClass support.

**Comment by sknitelius** [comment]
Released with 0.1.0-beta1
